name: Deploy to AWS EC2

on:
    push:
        branches: [master]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: copy-code
              uses: actions/checkout@v6

            - name: Install Node js
              uses: actions/setup-node@v6
              with:
                  node-version: 24.13.0

            - name: Install Dependencies
              run: npm install --frozen-lockfile

            - name: Build App
              run: npm run build

    deploy:
        runs-on: ubuntu-latest
        needs: build
        steps:
            - name: copy-code
              uses: actions/checkout@v6

            - name: Install Node js
              uses: actions/setup-node@v6
              with:
                  node-version: 24.13.0

            - name: Install Dependencies
              run: npm install --frozen-lockfile

            - name: Build App
              run: npm run build

            - name: Deploy to EC2
              env:
                  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
                  EC2_HOST: ${{ secrets.EC2_HOST }}
                  EC2_USER: ${{ secrets.EC2_USER }}
              run: |
                  mkdir -p ~/.ssh
                  echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
                  chmod 600 ~/.ssh/id_rsa

                  # Start the ssh-agent and add your key locally on the runner
                  eval `ssh-agent -s`
                  ssh-add ~/.ssh/id_rsa

                  ssh-keyscan -H "$EC2_HOST" >> ~/.ssh/known_hosts

                  # Copy files to EC2
                  rsync -avz --delete \
                    -e "ssh -i ~/.ssh/id_rsa" \
                    ./ $EC2_USER@$EC2_HOST:/home/ubuntu/project/backend/ecommerce-server

                  # Restart app
                  ssh -i ~/.ssh/id_rsa $EC2_USER@$EC2_HOST << 'EOF'
                      export NVM_DIR="$HOME/.nvm"
                      [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

                      cd /home/ubuntu/project/backend/ecommerce-server

                      npm install --frozen-lockfile
                      npm run build

                      pm2 startOrRestart ../ecosystem.config.js --env production
                      pm2 save
                  EOF
